language: ruby
rvm: 2.1.1
install: gem install kwalify
before_install: wget https://loot.github.io/masterlist.schema.yaml
script:
  - grep --line-number --basic-regexp "name: [^']" masterlist.yaml || true
  - kwalify -f masterlist.schema.yaml masterlist.yaml
  # The below is a hack as `kwalify` doesn't return with a non-zero exist code
  # when the "kwalification" fails, so this forces an error if there are any
  # errors in the file being validated.
  - return $(kwalify -q -f masterlist.schema.yaml masterlist.yaml|wc -l)

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
